# Since there are only subdirectories (no source files), we just need to add them here.
add_subdirectory(common)
add_subdirectory(classical)
add_subdirectory(block_cipher)
add_subdirectory(hash_functions)
add_subdirectory(check_sum)
add_subdirectory(stream_cipher)
add_subdirectory(public_key)
add_subdirectory(pseudo_random_generator)