#ifndef ADFGVXTEST_HPP
#define ADFGVXTEST_HPP

#include <gtest/gtest.h>
#include "../src/Adfgvx.hpp"

class AdfgvxTest : public ::testing::Test
{
protected:
   Adfgvx *A;

   virtual void SetUp()
   {
      A = new Adfgvx("GABRIEL", "C1OFWJYMT5B4I7A28SP30QHXKEUL6DVRGZN9");
   }

   virtual void TearDown()
   {
      delete A;
   }
};

TEST_F(AdfgvxTest, encode)
{
   const std::string clear_text = "SALUTNILILPARAITQUETUCONNAISLAPROGRAMMATIONORIENTEEOBJETSURLEBOUTDESDOIGTS";

   EXPECT_EQ("XDGFAVAFGAFDVVDAXVFFAXFFFFDDAFFFDFADVXVDDXXXGFGFGVVFAXDADDFDDAXAFXFFVAFFAVVDFFX"
           "AVVFGVDFXVVVDGFXAGFDAXVADXVVXDXVAGFVFXXXDFFFFDFVFVFFXFXAXFDFFFXDFFXDVFDFVFX", A->encode(clear_text));
}

TEST_F(AdfgvxTest, decode)
{
   const std::string clear_text = "SALUTNILILPARAITQUETUCONNAISLAPROGRAMMATIONORIENTEEOBJETSURLEBOUTDESDOIGTS999";

   EXPECT_EQ(clear_text, A->decode("XDGFAVAFGAFDVVDAXVFFAXFFFFDDAFFFDFADVXVDDXXXGFGFGVVFAXDADDFDDAXAFXFFVAFFAVVDFFX"
           "AVVFGVDFXVVVDGFXAGFDAXVADXVVXDXVAGFVFXXXDFFFFDFVFVFFXFXAXFDFFFXDFFXDVFDFVFX"));
}

#endif