#ifndef RAILFENCETEST_HPP
#define RAILFENCETEST_HPP

#include <gtest/gtest.h>
#include "../src/Railfence.hpp"

class RailfenceTest : public ::testing::Test
{
protected:
   Railfence *R;

   virtual void SetUp()
   {
      R = new Railfence(6);
   }

   virtual void TearDown()
   {
      delete R;
   }
};

TEST_F(RailfenceTest, encode)
{
   const ClassicalType clear_text = "SALUTNILILPARAITQUETUCONNAISLAPROGRAMMATIONORIENTEEOBJETSURLEBOUTDESDOIGTS";

   EXPECT_EQ("SPUPIEEIALATCARTOEOLBOGLIREOLOANTBRODTULAUNSGMONJUUSSTIIQNIRMREESTENTAAITD", R->encode(clear_text));
}

TEST_F(RailfenceTest, decode)
{
   const ClassicalType clear_text = "SALUTNILILPARAITQUETUCONNAISLAPROGRAMMATIONORIENTEEOBJETSURLEBOUTDESDOIGTS";

   EXPECT_EQ(clear_text, R->decode("SPUPIEEIALATCARTOEOLBOGLIREOLOANTBRODTULAUNSGMONJUUSSTIIQNIRMREESTENTAAITD"));
}

TEST_F(RailfenceTest, encodeWithOffset)
{
   const ClassicalType clear_text = "SALUTNILILPARAITQUETUCONNAISLAPROGRAMMATIONORIENTEEOBJETSURLEBOUTDESDOIGTS";

   R->setOffset(4);
   // IQIMESE NLTUATAMINTUDS TIIENLRARTERTD ULATNAGTOEJLUOS SLPRUOPOINEBEOIT AACROOBG
   EXPECT_EQ("IQIMESENLTUASAMINTUDSTIIENLRARTERTDULATNAGTOEJLUOSSLPRUOPOINEBEOITAACROOBG", R->encode(clear_text));
}

TEST_F(RailfenceTest, decodeWithOffset)
{
   const ClassicalType clear_text = "SALUTNILILPARAITQUETUCONNAISLAPROGRAMMATIONORIENTEEOBJETSURLEBOUTDESDOIGTS";

   R->setOffset(4);
   EXPECT_EQ(clear_text, R->decode("IQIMESENLTUASAMINTUDSTIIENLRARTERTDULATNAGTOEJLUOSSLPRUOPOINEBEOITAACROOBG"));
}

#endif